### ISSUE TITLE
doesnt save settings

### ISSUE THREAD

**Issue by tiagoefreitas** [crocokyle/XMRGUI#1]
I tried using it but it doesnt save my settings, when I click Mine it changes back to default settings and mines to the developer wallet. 
When I stop mining it shows my wallet again.
If I close and reopen the program it shows default again, never saves my settings even if I click Save

**Comment by crocokyle** [comment]
Hey, I think a lot of people are getting confused because of the way I wrote the program. I'm working on a solution to make this a little easier to understand, but initially...the miner switches to the dev wallet to mine for 1 or 2 minutes depending on what you have the donation set at. After that, it will switch back to your own information. If it's not switching back to your address afterward, please let me know because that would be a major issue. If it isn't saving I'd like to try a TeamViewer session if you're available so I can see the issue in action. You can also try to contact me via the live chat on my [website](http://xmrgui.com) as I might answer more frequently.
